//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaTruc
    {
        public int ct_id { get; set; }
        public System.DateTime ct_ngaytruc { get; set; }
        public string ct_buoitruc { get; set; }
        public string nv_id { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
