//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public int cthd_soluong { get; set; }
        public string hd_id { get; set; }
        public int tu_id { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual ThucUong ThucUong { get; set; }
    }
}
