//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon_InBaoCao
    {
        public string hd_id { get; set; }
        public System.DateTime hd_ngaylap { get; set; }
        public Nullable<int> hd_phuthu { get; set; }
        public Nullable<int> hd_giamgia { get; set; }
        public int hd_tongtien { get; set; }
        public int hd_trangthai { get; set; }
        public string ban_id { get; set; }
        public string nv_ten { get; set; }
    }
}
