//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CafeDataBaseEntities1 : DbContext
    {
        public CafeDataBaseEntities1()
            : base("name=CafeDataBaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ban> Bans { get; set; }
        public virtual DbSet<CaTruc> CaTrucs { get; set; }
        public virtual DbSet<CTHD> CTHDs { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhuVuc> KhuVucs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<ThucUong> ThucUongs { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<HoaDon_InBaoCao> HoaDon_InBaoCao { get; set; }
        public virtual DbSet<HoaDon_InThongKe> HoaDon_InThongKe { get; set; }
        public virtual DbSet<HoaDon_InThongKe2> HoaDon_InThongKe2 { get; set; }
        public virtual DbSet<HoaDon_ThongKeMaHD> HoaDon_ThongKeMaHD { get; set; }
    
        public virtual int Ban_CapNhatTrangThaiBan(string ban_id, string trangthai)
        {
            var ban_idParameter = ban_id != null ?
                new ObjectParameter("ban_id", ban_id) :
                new ObjectParameter("ban_id", typeof(string));
    
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ban_CapNhatTrangThaiBan", ban_idParameter, trangthaiParameter);
        }
    
        public virtual ObjectResult<Ban_KiemTraTenBanTrung_Result> Ban_KiemTraTenBanTrung(string ban_ten)
        {
            var ban_tenParameter = ban_ten != null ?
                new ObjectParameter("ban_ten", ban_ten) :
                new ObjectParameter("ban_ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ban_KiemTraTenBanTrung_Result>("Ban_KiemTraTenBanTrung", ban_tenParameter);
        }
    
        public virtual ObjectResult<string> Ban_KiemTraTrangThai_TheoIdBan(string ban_id)
        {
            var ban_idParameter = ban_id != null ?
                new ObjectParameter("ban_id", ban_id) :
                new ObjectParameter("ban_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Ban_KiemTraTrangThai_TheoIdBan", ban_idParameter);
        }
    
        public virtual ObjectResult<Ban_Load_Result> Ban_Load()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ban_Load_Result>("Ban_Load");
        }
    
        public virtual ObjectResult<Ban_Load_BanTrangThaiCoKhach_Result> Ban_Load_BanTrangThaiCoKhach()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ban_Load_BanTrangThaiCoKhach_Result>("Ban_Load_BanTrangThaiCoKhach");
        }
    
        public virtual ObjectResult<Ban_Load_KhuVuc_Result> Ban_Load_KhuVuc(Nullable<int> kv_id)
        {
            var kv_idParameter = kv_id.HasValue ?
                new ObjectParameter("kv_id", kv_id) :
                new ObjectParameter("kv_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ban_Load_KhuVuc_Result>("Ban_Load_KhuVuc", kv_idParameter);
        }
    
        public virtual ObjectResult<Ban_Load_LoaiTru1BanTrung_TrangThaiCoKhach_Result> Ban_Load_LoaiTru1BanTrung_TrangThaiCoKhach(string maban)
        {
            var mabanParameter = maban != null ?
                new ObjectParameter("maban", maban) :
                new ObjectParameter("maban", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ban_Load_LoaiTru1BanTrung_TrangThaiCoKhach_Result>("Ban_Load_LoaiTru1BanTrung_TrangThaiCoKhach", mabanParameter);
        }
    
        public virtual ObjectResult<Ban_Load_TrangThai_Result> Ban_Load_TrangThai(string trangthai)
        {
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ban_Load_TrangThai_Result>("Ban_Load_TrangThai", trangthaiParameter);
        }
    
        public virtual int Ban_Sua(string ban_id, string ban_ten, string ban_trangthai, string kv_id)
        {
            var ban_idParameter = ban_id != null ?
                new ObjectParameter("ban_id", ban_id) :
                new ObjectParameter("ban_id", typeof(string));
    
            var ban_tenParameter = ban_ten != null ?
                new ObjectParameter("ban_ten", ban_ten) :
                new ObjectParameter("ban_ten", typeof(string));
    
            var ban_trangthaiParameter = ban_trangthai != null ?
                new ObjectParameter("ban_trangthai", ban_trangthai) :
                new ObjectParameter("ban_trangthai", typeof(string));
    
            var kv_idParameter = kv_id != null ?
                new ObjectParameter("kv_id", kv_id) :
                new ObjectParameter("kv_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ban_Sua", ban_idParameter, ban_tenParameter, ban_trangthaiParameter, kv_idParameter);
        }
    
        public virtual int Ban_Them(string ban_id, string ban_ten, string ban_trangthai, string kv_id, Nullable<int> ban_xoa)
        {
            var ban_idParameter = ban_id != null ?
                new ObjectParameter("ban_id", ban_id) :
                new ObjectParameter("ban_id", typeof(string));
    
            var ban_tenParameter = ban_ten != null ?
                new ObjectParameter("ban_ten", ban_ten) :
                new ObjectParameter("ban_ten", typeof(string));
    
            var ban_trangthaiParameter = ban_trangthai != null ?
                new ObjectParameter("ban_trangthai", ban_trangthai) :
                new ObjectParameter("ban_trangthai", typeof(string));
    
            var kv_idParameter = kv_id != null ?
                new ObjectParameter("kv_id", kv_id) :
                new ObjectParameter("kv_id", typeof(string));
    
            var ban_xoaParameter = ban_xoa.HasValue ?
                new ObjectParameter("ban_xoa", ban_xoa) :
                new ObjectParameter("ban_xoa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ban_Them", ban_idParameter, ban_tenParameter, ban_trangthaiParameter, kv_idParameter, ban_xoaParameter);
        }
    
        public virtual int Ban_TimIDKeTiep()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ban_TimIDKeTiep");
        }
    
        public virtual int Ban_Xoa(string ban_id)
        {
            var ban_idParameter = ban_id != null ?
                new ObjectParameter("ban_id", ban_id) :
                new ObjectParameter("ban_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Ban_Xoa", ban_idParameter);
        }
    
        public virtual int CTHD_HuyBan(string hd_id)
        {
            var hd_idParameter = hd_id != null ?
                new ObjectParameter("hd_id", hd_id) :
                new ObjectParameter("hd_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CTHD_HuyBan", hd_idParameter);
        }
    
        public virtual ObjectResult<CTHD_KiemTraThucUongCoTrongCTHD_Result> CTHD_KiemTraThucUongCoTrongCTHD(Nullable<int> tu_id, string hd_id)
        {
            var tu_idParameter = tu_id.HasValue ?
                new ObjectParameter("tu_id", tu_id) :
                new ObjectParameter("tu_id", typeof(int));
    
            var hd_idParameter = hd_id != null ?
                new ObjectParameter("hd_id", hd_id) :
                new ObjectParameter("hd_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTHD_KiemTraThucUongCoTrongCTHD_Result>("CTHD_KiemTraThucUongCoTrongCTHD", tu_idParameter, hd_idParameter);
        }
    
        public virtual ObjectResult<CTHD_Load_DonGia_TinhThanhTien_Result> CTHD_Load_DonGia_TinhThanhTien(string hd_id)
        {
            var hd_idParameter = hd_id != null ?
                new ObjectParameter("hd_id", hd_id) :
                new ObjectParameter("hd_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTHD_Load_DonGia_TinhThanhTien_Result>("CTHD_Load_DonGia_TinhThanhTien", hd_idParameter);
        }
    
        public virtual ObjectResult<CTHD_Load_IDHoaDon_Result> CTHD_Load_IDHoaDon(string hd_ma)
        {
            var hd_maParameter = hd_ma != null ?
                new ObjectParameter("hd_ma", hd_ma) :
                new ObjectParameter("hd_ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CTHD_Load_IDHoaDon_Result>("CTHD_Load_IDHoaDon", hd_maParameter);
        }
    
        public virtual int CTHD_Sua(Nullable<int> cthd_soluong, string hd_id, Nullable<int> tu_id)
        {
            var cthd_soluongParameter = cthd_soluong.HasValue ?
                new ObjectParameter("cthd_soluong", cthd_soluong) :
                new ObjectParameter("cthd_soluong", typeof(int));
    
            var hd_idParameter = hd_id != null ?
                new ObjectParameter("hd_id", hd_id) :
                new ObjectParameter("hd_id", typeof(string));
    
            var tu_idParameter = tu_id.HasValue ?
                new ObjectParameter("tu_id", tu_id) :
                new ObjectParameter("tu_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CTHD_Sua", cthd_soluongParameter, hd_idParameter, tu_idParameter);
        }
    
        public virtual int CTHD_Them(Nullable<int> cthd_soluong, string hd_id, Nullable<int> tu_id)
        {
            var cthd_soluongParameter = cthd_soluong.HasValue ?
                new ObjectParameter("cthd_soluong", cthd_soluong) :
                new ObjectParameter("cthd_soluong", typeof(int));
    
            var hd_idParameter = hd_id != null ?
                new ObjectParameter("hd_id", hd_id) :
                new ObjectParameter("hd_id", typeof(string));
    
            var tu_idParameter = tu_id.HasValue ?
                new ObjectParameter("tu_id", tu_id) :
                new ObjectParameter("tu_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CTHD_Them", cthd_soluongParameter, hd_idParameter, tu_idParameter);
        }
    
        public virtual int CTHD_Xoa(string hd_id, Nullable<int> tu_id)
        {
            var hd_idParameter = hd_id != null ?
                new ObjectParameter("hd_id", hd_id) :
                new ObjectParameter("hd_id", typeof(string));
    
            var tu_idParameter = tu_id.HasValue ?
                new ObjectParameter("tu_id", tu_id) :
                new ObjectParameter("tu_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CTHD_Xoa", hd_idParameter, tu_idParameter);
        }
    
        public virtual ObjectResult<DanhMuc_Load_Result> DanhMuc_Load()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DanhMuc_Load_Result>("DanhMuc_Load");
        }
    
        public virtual int DanhMuc_Sua(Nullable<int> dm_id, string dm_ten, Nullable<int> dm_trangthai, string dm_ghichu)
        {
            var dm_idParameter = dm_id.HasValue ?
                new ObjectParameter("dm_id", dm_id) :
                new ObjectParameter("dm_id", typeof(int));
    
            var dm_tenParameter = dm_ten != null ?
                new ObjectParameter("dm_ten", dm_ten) :
                new ObjectParameter("dm_ten", typeof(string));
    
            var dm_trangthaiParameter = dm_trangthai.HasValue ?
                new ObjectParameter("dm_trangthai", dm_trangthai) :
                new ObjectParameter("dm_trangthai", typeof(int));
    
            var dm_ghichuParameter = dm_ghichu != null ?
                new ObjectParameter("dm_ghichu", dm_ghichu) :
                new ObjectParameter("dm_ghichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DanhMuc_Sua", dm_idParameter, dm_tenParameter, dm_trangthaiParameter, dm_ghichuParameter);
        }
    
        public virtual int DanhMuc_Them(string dm_ten, Nullable<int> dm_trangthai, string dm_ghichu)
        {
            var dm_tenParameter = dm_ten != null ?
                new ObjectParameter("dm_ten", dm_ten) :
                new ObjectParameter("dm_ten", typeof(string));
    
            var dm_trangthaiParameter = dm_trangthai.HasValue ?
                new ObjectParameter("dm_trangthai", dm_trangthai) :
                new ObjectParameter("dm_trangthai", typeof(int));
    
            var dm_ghichuParameter = dm_ghichu != null ?
                new ObjectParameter("dm_ghichu", dm_ghichu) :
                new ObjectParameter("dm_ghichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DanhMuc_Them", dm_tenParameter, dm_trangthaiParameter, dm_ghichuParameter);
        }
    
        public virtual int DanhMuc_Xoa(Nullable<int> dm_id)
        {
            var dm_idParameter = dm_id.HasValue ?
                new ObjectParameter("dm_id", dm_id) :
                new ObjectParameter("dm_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DanhMuc_Xoa", dm_idParameter);
        }
    
        public virtual int HoaDon_DoiBan(string mabanChon, string mabanDoi)
        {
            var mabanChonParameter = mabanChon != null ?
                new ObjectParameter("mabanChon", mabanChon) :
                new ObjectParameter("mabanChon", typeof(string));
    
            var mabanDoiParameter = mabanDoi != null ?
                new ObjectParameter("mabanDoi", mabanDoi) :
                new ObjectParameter("mabanDoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HoaDon_DoiBan", mabanChonParameter, mabanDoiParameter);
        }
    
        public virtual int HoaDon_HuyBan(string hd_id)
        {
            var hd_idParameter = hd_id != null ?
                new ObjectParameter("hd_id", hd_id) :
                new ObjectParameter("hd_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HoaDon_HuyBan", hd_idParameter);
        }
    
        public virtual ObjectResult<HoaDon_In_Result> HoaDon_In(string mahd)
        {
            var mahdParameter = mahd != null ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_In_Result>("HoaDon_In", mahdParameter);
        }
    
        public virtual ObjectResult<HoaDon_InBaoCaoTheoTuyChon_Result> HoaDon_InBaoCaoTheoTuyChon(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_InBaoCaoTheoTuyChon_Result>("HoaDon_InBaoCaoTheoTuyChon", tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<HoaDon_LayHoaDonTheoMaBan_Result> HoaDon_LayHoaDonTheoMaBan(string maban)
        {
            var mabanParameter = maban != null ?
                new ObjectParameter("maban", maban) :
                new ObjectParameter("maban", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_LayHoaDonTheoMaBan_Result>("HoaDon_LayHoaDonTheoMaBan", mabanParameter);
        }
    
        public virtual ObjectResult<HoaDon_Load_Result> HoaDon_Load()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_Load_Result>("HoaDon_Load");
        }
    
        public virtual ObjectResult<HoaDon_Load_IDBan_TrangThaiHD_Result> HoaDon_Load_IDBan_TrangThaiHD(string ban_id)
        {
            var ban_idParameter = ban_id != null ?
                new ObjectParameter("ban_id", ban_id) :
                new ObjectParameter("ban_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_Load_IDBan_TrangThaiHD_Result>("HoaDon_Load_IDBan_TrangThaiHD", ban_idParameter);
        }
    
        public virtual int HoaDon_Sua(string hd_id, Nullable<System.DateTime> hd_ngaylap, Nullable<int> hd_trangthai, Nullable<int> hd_phuthu, Nullable<int> hd_giamgia, Nullable<double> hd_tongtien, string ban_id, string nv_id)
        {
            var hd_idParameter = hd_id != null ?
                new ObjectParameter("hd_id", hd_id) :
                new ObjectParameter("hd_id", typeof(string));
    
            var hd_ngaylapParameter = hd_ngaylap.HasValue ?
                new ObjectParameter("hd_ngaylap", hd_ngaylap) :
                new ObjectParameter("hd_ngaylap", typeof(System.DateTime));
    
            var hd_trangthaiParameter = hd_trangthai.HasValue ?
                new ObjectParameter("hd_trangthai", hd_trangthai) :
                new ObjectParameter("hd_trangthai", typeof(int));
    
            var hd_phuthuParameter = hd_phuthu.HasValue ?
                new ObjectParameter("hd_phuthu", hd_phuthu) :
                new ObjectParameter("hd_phuthu", typeof(int));
    
            var hd_giamgiaParameter = hd_giamgia.HasValue ?
                new ObjectParameter("hd_giamgia", hd_giamgia) :
                new ObjectParameter("hd_giamgia", typeof(int));
    
            var hd_tongtienParameter = hd_tongtien.HasValue ?
                new ObjectParameter("hd_tongtien", hd_tongtien) :
                new ObjectParameter("hd_tongtien", typeof(double));
    
            var ban_idParameter = ban_id != null ?
                new ObjectParameter("ban_id", ban_id) :
                new ObjectParameter("ban_id", typeof(string));
    
            var nv_idParameter = nv_id != null ?
                new ObjectParameter("nv_id", nv_id) :
                new ObjectParameter("nv_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HoaDon_Sua", hd_idParameter, hd_ngaylapParameter, hd_trangthaiParameter, hd_phuthuParameter, hd_giamgiaParameter, hd_tongtienParameter, ban_idParameter, nv_idParameter);
        }
    
        public virtual int HoaDon_Them(string hd_id, Nullable<System.DateTime> hd_ngaylap, Nullable<int> hd_trangthai, Nullable<int> hd_phuthu, Nullable<int> hd_giamgia, Nullable<double> hd_tongtien, string ban_id, string nv_id)
        {
            var hd_idParameter = hd_id != null ?
                new ObjectParameter("hd_id", hd_id) :
                new ObjectParameter("hd_id", typeof(string));
    
            var hd_ngaylapParameter = hd_ngaylap.HasValue ?
                new ObjectParameter("hd_ngaylap", hd_ngaylap) :
                new ObjectParameter("hd_ngaylap", typeof(System.DateTime));
    
            var hd_trangthaiParameter = hd_trangthai.HasValue ?
                new ObjectParameter("hd_trangthai", hd_trangthai) :
                new ObjectParameter("hd_trangthai", typeof(int));
    
            var hd_phuthuParameter = hd_phuthu.HasValue ?
                new ObjectParameter("hd_phuthu", hd_phuthu) :
                new ObjectParameter("hd_phuthu", typeof(int));
    
            var hd_giamgiaParameter = hd_giamgia.HasValue ?
                new ObjectParameter("hd_giamgia", hd_giamgia) :
                new ObjectParameter("hd_giamgia", typeof(int));
    
            var hd_tongtienParameter = hd_tongtien.HasValue ?
                new ObjectParameter("hd_tongtien", hd_tongtien) :
                new ObjectParameter("hd_tongtien", typeof(double));
    
            var ban_idParameter = ban_id != null ?
                new ObjectParameter("ban_id", ban_id) :
                new ObjectParameter("ban_id", typeof(string));
    
            var nv_idParameter = nv_id != null ?
                new ObjectParameter("nv_id", nv_id) :
                new ObjectParameter("nv_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HoaDon_Them", hd_idParameter, hd_ngaylapParameter, hd_trangthaiParameter, hd_phuthuParameter, hd_giamgiaParameter, hd_tongtienParameter, ban_idParameter, nv_idParameter);
        }
    
        public virtual ObjectResult<HoaDon_ThongKeTheoNgayLap_Result> HoaDon_ThongKeTheoNgayLap(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_ThongKeTheoNgayLap_Result>("HoaDon_ThongKeTheoNgayLap", tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<HoaDon_ThongKeTheoNhanVien_Result> HoaDon_ThongKeTheoNhanVien(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_ThongKeTheoNhanVien_Result>("HoaDon_ThongKeTheoNhanVien", manvParameter);
        }
    
        public virtual ObjectResult<HoaDon_ThongKeTheoNhanVienTheoNgayLap_Result> HoaDon_ThongKeTheoNhanVienTheoNgayLap(string manv, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HoaDon_ThongKeTheoNhanVienTheoNgayLap_Result>("HoaDon_ThongKeTheoNhanVienTheoNgayLap", manvParameter, tungayParameter, denngayParameter);
        }
    
        public virtual int HoaDon_Xoa(string hd_ma)
        {
            var hd_maParameter = hd_ma != null ?
                new ObjectParameter("hd_ma", hd_ma) :
                new ObjectParameter("hd_ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HoaDon_Xoa", hd_maParameter);
        }
    
        public virtual ObjectResult<KhucVuc_Load_Result> KhucVuc_Load()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhucVuc_Load_Result>("KhucVuc_Load");
        }
    
        public virtual ObjectResult<KhuVuc_LoadTheoTrangThai_Result> KhuVuc_LoadTheoTrangThai(string trangthai)
        {
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KhuVuc_LoadTheoTrangThai_Result>("KhuVuc_LoadTheoTrangThai", trangthaiParameter);
        }
    
        public virtual int KhuVuc_Sua(Nullable<int> kv_id, string kv_ten, string kv_trangthai, string kv_ghichu)
        {
            var kv_idParameter = kv_id.HasValue ?
                new ObjectParameter("kv_id", kv_id) :
                new ObjectParameter("kv_id", typeof(int));
    
            var kv_tenParameter = kv_ten != null ?
                new ObjectParameter("kv_ten", kv_ten) :
                new ObjectParameter("kv_ten", typeof(string));
    
            var kv_trangthaiParameter = kv_trangthai != null ?
                new ObjectParameter("kv_trangthai", kv_trangthai) :
                new ObjectParameter("kv_trangthai", typeof(string));
    
            var kv_ghichuParameter = kv_ghichu != null ?
                new ObjectParameter("kv_ghichu", kv_ghichu) :
                new ObjectParameter("kv_ghichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KhuVuc_Sua", kv_idParameter, kv_tenParameter, kv_trangthaiParameter, kv_ghichuParameter);
        }
    
        public virtual int KhuVuc_Them(string kv_ten, string kv_trangthai, string kv_ghichu)
        {
            var kv_tenParameter = kv_ten != null ?
                new ObjectParameter("kv_ten", kv_ten) :
                new ObjectParameter("kv_ten", typeof(string));
    
            var kv_trangthaiParameter = kv_trangthai != null ?
                new ObjectParameter("kv_trangthai", kv_trangthai) :
                new ObjectParameter("kv_trangthai", typeof(string));
    
            var kv_ghichuParameter = kv_ghichu != null ?
                new ObjectParameter("kv_ghichu", kv_ghichu) :
                new ObjectParameter("kv_ghichu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KhuVuc_Them", kv_tenParameter, kv_trangthaiParameter, kv_ghichuParameter);
        }
    
        public virtual int KhuVuc_Xoa(Nullable<int> kv_id)
        {
            var kv_idParameter = kv_id.HasValue ?
                new ObjectParameter("kv_id", kv_id) :
                new ObjectParameter("kv_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KhuVuc_Xoa", kv_idParameter);
        }
    
        public virtual ObjectResult<LayIDKeTiep_Result> LayIDKeTiep()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayIDKeTiep_Result>("LayIDKeTiep");
        }
    
        public virtual int NhanVien_CapNhatNhanVienCoTaiKhoan(string nv_id, Nullable<int> nv_taikhoan)
        {
            var nv_idParameter = nv_id != null ?
                new ObjectParameter("nv_id", nv_id) :
                new ObjectParameter("nv_id", typeof(string));
    
            var nv_taikhoanParameter = nv_taikhoan.HasValue ?
                new ObjectParameter("nv_taikhoan", nv_taikhoan) :
                new ObjectParameter("nv_taikhoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVien_CapNhatNhanVienCoTaiKhoan", nv_idParameter, nv_taikhoanParameter);
        }
    
        public virtual ObjectResult<NhanVien_Load_Result> NhanVien_Load()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhanVien_Load_Result>("NhanVien_Load");
        }
    
        public virtual ObjectResult<NhanVien_LoadNhanVienTheoMa_Result> NhanVien_LoadNhanVienTheoMa(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhanVien_LoadNhanVienTheoMa_Result>("NhanVien_LoadNhanVienTheoMa", manvParameter);
        }
    
        public virtual ObjectResult<NhanVien_LoadNVChuaCoTaiKhoan_Result> NhanVien_LoadNVChuaCoTaiKhoan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhanVien_LoadNVChuaCoTaiKhoan_Result>("NhanVien_LoadNVChuaCoTaiKhoan");
        }
    
        public virtual int NhanVien_Sua(string nv_id, string nv_ten, string nv_diachi, string nv_sdt, Nullable<int> nv_taikhoan, string nv_trangthai)
        {
            var nv_idParameter = nv_id != null ?
                new ObjectParameter("nv_id", nv_id) :
                new ObjectParameter("nv_id", typeof(string));
    
            var nv_tenParameter = nv_ten != null ?
                new ObjectParameter("nv_ten", nv_ten) :
                new ObjectParameter("nv_ten", typeof(string));
    
            var nv_diachiParameter = nv_diachi != null ?
                new ObjectParameter("nv_diachi", nv_diachi) :
                new ObjectParameter("nv_diachi", typeof(string));
    
            var nv_sdtParameter = nv_sdt != null ?
                new ObjectParameter("nv_sdt", nv_sdt) :
                new ObjectParameter("nv_sdt", typeof(string));
    
            var nv_taikhoanParameter = nv_taikhoan.HasValue ?
                new ObjectParameter("nv_taikhoan", nv_taikhoan) :
                new ObjectParameter("nv_taikhoan", typeof(int));
    
            var nv_trangthaiParameter = nv_trangthai != null ?
                new ObjectParameter("nv_trangthai", nv_trangthai) :
                new ObjectParameter("nv_trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVien_Sua", nv_idParameter, nv_tenParameter, nv_diachiParameter, nv_sdtParameter, nv_taikhoanParameter, nv_trangthaiParameter);
        }
    
        public virtual int NhanVien_Them(string nv_id, string nv_ten, string nv_diachi, string nv_sdt, Nullable<int> nv_taikhoan, string nv_trangthai)
        {
            var nv_idParameter = nv_id != null ?
                new ObjectParameter("nv_id", nv_id) :
                new ObjectParameter("nv_id", typeof(string));
    
            var nv_tenParameter = nv_ten != null ?
                new ObjectParameter("nv_ten", nv_ten) :
                new ObjectParameter("nv_ten", typeof(string));
    
            var nv_diachiParameter = nv_diachi != null ?
                new ObjectParameter("nv_diachi", nv_diachi) :
                new ObjectParameter("nv_diachi", typeof(string));
    
            var nv_sdtParameter = nv_sdt != null ?
                new ObjectParameter("nv_sdt", nv_sdt) :
                new ObjectParameter("nv_sdt", typeof(string));
    
            var nv_taikhoanParameter = nv_taikhoan.HasValue ?
                new ObjectParameter("nv_taikhoan", nv_taikhoan) :
                new ObjectParameter("nv_taikhoan", typeof(int));
    
            var nv_trangthaiParameter = nv_trangthai != null ?
                new ObjectParameter("nv_trangthai", nv_trangthai) :
                new ObjectParameter("nv_trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVien_Them", nv_idParameter, nv_tenParameter, nv_diachiParameter, nv_sdtParameter, nv_taikhoanParameter, nv_trangthaiParameter);
        }
    
        public virtual int NhanVien_TimIDKeTiep()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVien_TimIDKeTiep");
        }
    
        public virtual int NhanVien_Xoa(string nv_id)
        {
            var nv_idParameter = nv_id != null ?
                new ObjectParameter("nv_id", nv_id) :
                new ObjectParameter("nv_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NhanVien_Xoa", nv_idParameter);
        }
    
        public virtual ObjectResult<TaiKhoan_LayQuyenTruyCap_Result> TaiKhoan_LayQuyenTruyCap(string tk_ma)
        {
            var tk_maParameter = tk_ma != null ?
                new ObjectParameter("tk_ma", tk_ma) :
                new ObjectParameter("tk_ma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TaiKhoan_LayQuyenTruyCap_Result>("TaiKhoan_LayQuyenTruyCap", tk_maParameter);
        }
    
        public virtual ObjectResult<TaiKhoan_Load_Result> TaiKhoan_Load()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TaiKhoan_Load_Result>("TaiKhoan_Load");
        }
    
        public virtual ObjectResult<TaiKhoan_Load_nv_id_Result> TaiKhoan_Load_nv_id(string nv_id, string tk_matkhau)
        {
            var nv_idParameter = nv_id != null ?
                new ObjectParameter("nv_id", nv_id) :
                new ObjectParameter("nv_id", typeof(string));
    
            var tk_matkhauParameter = tk_matkhau != null ?
                new ObjectParameter("tk_matkhau", tk_matkhau) :
                new ObjectParameter("tk_matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TaiKhoan_Load_nv_id_Result>("TaiKhoan_Load_nv_id", nv_idParameter, tk_matkhauParameter);
        }
    
        public virtual int TaiKhoan_Sua(string nv_id, string tk_matkhau, Nullable<int> tk_quyen, Nullable<int> tk_trangthai)
        {
            var nv_idParameter = nv_id != null ?
                new ObjectParameter("nv_id", nv_id) :
                new ObjectParameter("nv_id", typeof(string));
    
            var tk_matkhauParameter = tk_matkhau != null ?
                new ObjectParameter("tk_matkhau", tk_matkhau) :
                new ObjectParameter("tk_matkhau", typeof(string));
    
            var tk_quyenParameter = tk_quyen.HasValue ?
                new ObjectParameter("tk_quyen", tk_quyen) :
                new ObjectParameter("tk_quyen", typeof(int));
    
            var tk_trangthaiParameter = tk_trangthai.HasValue ?
                new ObjectParameter("tk_trangthai", tk_trangthai) :
                new ObjectParameter("tk_trangthai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TaiKhoan_Sua", nv_idParameter, tk_matkhauParameter, tk_quyenParameter, tk_trangthaiParameter);
        }
    
        public virtual int TaiKhoan_Them(string nv_id, string tk_matkhau, Nullable<int> tk_quyen, Nullable<int> tk_trangthai)
        {
            var nv_idParameter = nv_id != null ?
                new ObjectParameter("nv_id", nv_id) :
                new ObjectParameter("nv_id", typeof(string));
    
            var tk_matkhauParameter = tk_matkhau != null ?
                new ObjectParameter("tk_matkhau", tk_matkhau) :
                new ObjectParameter("tk_matkhau", typeof(string));
    
            var tk_quyenParameter = tk_quyen.HasValue ?
                new ObjectParameter("tk_quyen", tk_quyen) :
                new ObjectParameter("tk_quyen", typeof(int));
    
            var tk_trangthaiParameter = tk_trangthai.HasValue ?
                new ObjectParameter("tk_trangthai", tk_trangthai) :
                new ObjectParameter("tk_trangthai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TaiKhoan_Them", nv_idParameter, tk_matkhauParameter, tk_quyenParameter, tk_trangthaiParameter);
        }
    
        public virtual int TaiKhoan_Xoa(string nv_id)
        {
            var nv_idParameter = nv_id != null ?
                new ObjectParameter("nv_id", nv_id) :
                new ObjectParameter("nv_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TaiKhoan_Xoa", nv_idParameter);
        }
    
        public virtual ObjectResult<ThucUong_Load_Result> ThucUong_Load()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThucUong_Load_Result>("ThucUong_Load");
        }
    
        public virtual ObjectResult<ThucUong_Load_IDDanhMuc_Result> ThucUong_Load_IDDanhMuc(Nullable<int> dm_id)
        {
            var dm_idParameter = dm_id.HasValue ?
                new ObjectParameter("dm_id", dm_id) :
                new ObjectParameter("dm_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThucUong_Load_IDDanhMuc_Result>("ThucUong_Load_IDDanhMuc", dm_idParameter);
        }
    
        public virtual int ThucUong_Sua(Nullable<int> tu_id, string tu_ten, Nullable<int> tu_gia, Nullable<int> tu_trangthai, Nullable<int> dm_id)
        {
            var tu_idParameter = tu_id.HasValue ?
                new ObjectParameter("tu_id", tu_id) :
                new ObjectParameter("tu_id", typeof(int));
    
            var tu_tenParameter = tu_ten != null ?
                new ObjectParameter("tu_ten", tu_ten) :
                new ObjectParameter("tu_ten", typeof(string));
    
            var tu_giaParameter = tu_gia.HasValue ?
                new ObjectParameter("tu_gia", tu_gia) :
                new ObjectParameter("tu_gia", typeof(int));
    
            var tu_trangthaiParameter = tu_trangthai.HasValue ?
                new ObjectParameter("tu_trangthai", tu_trangthai) :
                new ObjectParameter("tu_trangthai", typeof(int));
    
            var dm_idParameter = dm_id.HasValue ?
                new ObjectParameter("dm_id", dm_id) :
                new ObjectParameter("dm_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThucUong_Sua", tu_idParameter, tu_tenParameter, tu_giaParameter, tu_trangthaiParameter, dm_idParameter);
        }
    
        public virtual int ThucUong_Them(Nullable<int> tu_id, string tu_ten, Nullable<int> tu_gia, Nullable<int> tu_trangthai, Nullable<int> dm_id)
        {
            var tu_idParameter = tu_id.HasValue ?
                new ObjectParameter("tu_id", tu_id) :
                new ObjectParameter("tu_id", typeof(int));
    
            var tu_tenParameter = tu_ten != null ?
                new ObjectParameter("tu_ten", tu_ten) :
                new ObjectParameter("tu_ten", typeof(string));
    
            var tu_giaParameter = tu_gia.HasValue ?
                new ObjectParameter("tu_gia", tu_gia) :
                new ObjectParameter("tu_gia", typeof(int));
    
            var tu_trangthaiParameter = tu_trangthai.HasValue ?
                new ObjectParameter("tu_trangthai", tu_trangthai) :
                new ObjectParameter("tu_trangthai", typeof(int));
    
            var dm_idParameter = dm_id.HasValue ?
                new ObjectParameter("dm_id", dm_id) :
                new ObjectParameter("dm_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThucUong_Them", tu_idParameter, tu_tenParameter, tu_giaParameter, tu_trangthaiParameter, dm_idParameter);
        }
    
        public virtual int ThucUong_Xoa(Nullable<int> tu_id)
        {
            var tu_idParameter = tu_id.HasValue ?
                new ObjectParameter("tu_id", tu_id) :
                new ObjectParameter("tu_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThucUong_Xoa", tu_idParameter);
        }
    
        public virtual int TimIDKeTiep(string table)
        {
            var tableParameter = table != null ?
                new ObjectParameter("table", table) :
                new ObjectParameter("table", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimIDKeTiep", tableParameter);
        }
    }
}
